### PR TITLE
Add docs on how to fund local L2 account

### LINKED ISSUE #450: Deposits (messages) from PolygonZKEvm to L1 are stuck
While trying to integrate PolygonZKEvm in our local E2E tests at Beamer Bridge, we noticed an inconsistent behavior between the different runs of it (tests are flaky).
We've seen that sometimes we end up with successful relays and sometimes not.

We are using your `zkevm-bridge-service` repository to spin up a local PolygonZKEvm environment.

How our E2E testing flow looks likes:
1. Initialize/bring up the local (dockerized) PolygonZKEvm environment - https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L109-L111
2. Deploy Beamer protocol on PolygonZKEvm & Geth L1 - https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L117-L120
3. Run the E2E test (https://github.com/beamer-bridge/beamer/blob/main/docker/polygon_zkevm/polygon_zkevm.sh#L122-L124) which:
- Sends a message from L2 to L1 by submitting a call to [this contract function](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/FillManager.sol) after [creating a transfer request](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/RequestManager.sol#L338-L418). 
The `fillRequest` call will send a message to [our own PolygonZKEvm messengers](https://github.com/beamer-bridge/beamer/blob/main/contracts/contracts/chains/polygon_zkevm/PolygonZkEVMMessengers.sol) on L2 which will forward this message to the `PolygonZKEvmBridge` (on L2) by calling `PolygonZkEVMBridge.bridgeMessage(...)`
- Call our relayer which [waits for the message to be ready for claiming (relaying)](https://github.com/beamer-bridge/beamer/blob/main/relayer/src/services/relayer/polygon-zkevm.ts#L114-L194) after which it relays it (by calling `PolygonZkEVMBridge.claimMessage`) on L1
- Verify that the message arrived at the destination by scanning certain contract events (step not relevant for this bug report)

In order to reproduce the problem we are experiencing, one needs to:
- Clone our repository - `git clone --recurse-submodules https://github.com/beamer-bridge/beamer.git`
- Enter the beamer folder - `cd beamer`
- Checkout this branch - `git checkout polygon-zkevm-e2e-debug`
- Make the relayer binaries - `make relayers`
- Start up the local PolygonZKEvm environment - `./docker/polygon_zkevm/polygon_zkevm.sh up`
- Run `docker logs -f zkevm_node | grep ERROR` in one terminal. You will use this terminal to detect when the problem appears.
- Open another terminal and deploy beamer - `./docker/polygon_zkevm/polygon_zkevm.sh deploy-beamer`
- After contracts have been deployed, run the E2E tests by running `./docker/polygon_zkevm/polygon_zkevm.sh e2e-test` until the ERROR logs show up (this might mean that you need to run the `e2e-test` command multiple times until the logs appear). They should look something like:
```
2023-06-19T15:51:55.494Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: replacement transaction underpriced    {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
2023-06-19T15:51:56.501Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: nonce too low  {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
2023-06-19T15:51:57.507Z        ERROR   ethtxmanager/ethtxmanager.go:392        failed to send tx 0x21acf28535683372310c4c20d047d297133b1e974a24a831de26ee09d55a234c to network: nonce too low  {"pid": 1, "version": "v0.0.7", "monitoredTx": "sequence-from-18-to-18"}
```

Note: **Make sure you run all the above commands from the root of the project, otherwise they might not work.**

Once you start seeing the ERROR logs in the terminal, the state will stop synchronizing between L2 and L1 (future deposits/messages will never arrive/be included on L1) and therefore our e2e tests will hang forever at this log line: 
`Waiting for message to be ready for claiming.`

We already tested the same process on testnet (Goerli) and it was not possible to reproduce it there.

**This problem is present both with the latest version of your `develop` branch and at this commit: https://github.com/0xPolygonHermez/zkevm-bridge-service/tree/09e0247b335a19a5e16945e8e1e805e410e41ca3 (which is used on our `main` branch)**

### PR DESCRIPTION
**Pull request by compojoom**
Closes #450.

Add some docs on how to properly fund an account on L2. For more context check out:
https://github.com/0xPolygonHermez/zkevm-bridge-service/issues/450

### CODE REVIEW

**Comment by compojoom** [comment]
Ok, read the CLA, now what?

**Comment by ARR552** [comment]
@cla-bot check

**Comment by compojoom** [comment]
@ARR552 I don't understand what I'm supposed to do?

I clicked the links to the individual docs, but there is no button for accepting?

Am I supposed to make a PR against this file: https://github.com/0xPolygonHermez/clabot-config/blob/master/.clabot ?

**Comment by ARR552** [comment]
@cla-bot check

**Review by ARR552 — APPROVED** [review]

**Comment by compojoom** [comment]
@ARR552 thanks!

**Pull request merged**
